### ISSUE TITLE
pyasn1.error.SubstrateUnderrunError: 94-octet short

### ISSUE THREAD

**Issue by netllama** [lclevy/firepwd#7]
Trying to decrypt my firefox-66.0 passwords, and it fails with this exception:
```
$ python firepwd.py -d /home/netllama/.mozilla/firefox/3ceo1ujt.default/
 SEQUENCE {
   SEQUENCE {
     OBJECTIDENTIFIER 1.2.840.113549.1.12.5.1.3
     SEQUENCE {
       OCTETSTRING 431d93f0b321bc4b959671313316e1f3
       INTEGER 01
     }
   }
   OCTETSTRING 84f75cb183843b68f47312bf40574ee1
 }
password check? True
 SEQUENCE {
   SEQUENCE {
     OBJECTIDENTIFIER 1.2.840.113549.1.12.5.1.3
     SEQUENCE {
       OCTETSTRING ea7369ad0ec0f6d217984c8eb5944138c0258597
       INTEGER 01
     }
   }
   OCTETSTRING e29ec8b9a5ec21d2e1bd7e53caa179b10e6d693c02853ec75388177a73ef4d7b
 }
3deskey 1c265ef2ae23df4cc7fde5dc9e3bbad0024c1a8c1613e3e50808080808080808
Traceback (most recent call last):
  File "firepwd.py", line 300, in <module>
    logins = getLoginData()
  File "firepwd.py", line 180, in getLoginData
    logins.append( (decodeLoginData(encUsername), decodeLoginData(encPassword), row[1]) )
  File "firepwd.py", line 154, in decodeLoginData
    asn1data = decoder.decode(b64decode(data)) #first base64 decoding, then ASN1DERdecode
  File "/usr/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 1049, in __call__
    raise error.SubstrateUnderrunError('%d-octet short' % (length - len(substrate)))
pyasn1.error.SubstrateUnderrunError: 94-octet short
```

**Comment by lclevy** [comment]
is it protected using a master password ?
if yes, you must provide it using the -p parameter.
just tested successfully with FF 66.0.2

**Comment by netllama** [comment]
No, I'm not using a master password at all.

**Comment by lclevy** [comment]
Which version of pyasn1 are you using?

**Comment by netllama** [comment]
pyasn1 (0.3.7)
pyasn1-modules (0.1.5)

**Comment by lclevy** [comment]
Please try with the new version
